### PR TITLE
fix: removed the diff when default profile changes. Printed the current profile info instead

### PR DESCRIPTION
**Pull request by lifeizhou-ap**
**What**
- Removed the prompt if the default profile setting is changed
- Displayed the profile info in use
- Fixed the bug when the specified profile is not in the config file

**Rules with this change**
1.  When the config file does not exist and no profile name is specified in the command, create a config file and set a default profile with name 'default' in the file
2. When the config file does not exist and profile name is specified in the command, create a config file and set a default profile with specified profile name in the file
3. When profile name is not specified in the command line, use the profile with name 'default'. If 'default' does not exist, create the default profile with name 'default'
4. When the specified profile does not exist in the config file, create a default profile settings with the specified profile name
5. When the specified profile exist in the config file, do nothing

Screenshot 2024-09-25 at 3 19 12 PM
Screenshot 2024-09-25 at 3 19 50 PM

Screenshot 2024-09-25 at 3 20 32 PM
Screenshot 2024-09-25 at 3 20 56 PM
Screenshot 2024-09-25 at 3 21 10 PM

### CODE REVIEW

**Comment by codefromthecrypt** [comment]
when finished, if you can put into the PR a triple backticked shell output of what it looks like now, or a screen grab, thanks

**Review by michaelneale — APPROVED** [review]
very nice!

**Review by codefromthecrypt — APPROVED** [review]
love it.

food for thought: conflate --profile when there is none there with a hint. e.g. --profile openai makes a profile for that, similarly ollama. This would allow us to skip the detection loop

**Review by baxen — APPROVED** [review]
LGTM

**Pull request merged**
